name: hello world

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  hello:
    runs-on: macos-latest
    
    steps:
      - name: Hello Step
        run: echo "hello world"
