name: runs tests

on:
  push:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.16
      - name: Install Dependencies
        run: pnpm ci
      - name: Run Tests
        run: pnpm test
